[package]
name = "raft-nodes"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"] }
bincode = "1.3"
rand = "*"
tokio = { version = "1", features = ["full"] }
